name: Run bbs qiandao
on:
  workflow_dispatch:
  schedule:
    - cron: '1 16 * * *' # 每天00:01运行一次

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      HOSTNAME: ${{ secrets.HOSTNAME }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r ./.github/scripts/requirements.txt
      - run: python ./.github/scripts/qiandao.py
