name: Sign

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次，UTC时间0点

jobs:
  sign-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up OpenSSL
        run: sudo apt-get install -y openssl

      - name: Decode and save private key
        run: |
          echo "-----BEGIN PRIVATE KEY-----" > private_key.pem
          echo "${{ secrets.PRIVATE_KEY }}" | fold -w 64 >> private_key.pem
          echo "-----END PRIVATE KEY-----" >> private_key.pem

      - name: 创建目标文件夹
        run: mkdir -p sign

      - name: Generate current date
        run: echo $(date -u +%Y%m%d) > sign/date.txt

      - name: 使用私钥签名日期并生成Hex格式
        run: |
          openssl dgst -sha256 -sign private_key.pem sign/date.txt | xxd -p > sign/date.sig

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add sign/date.txt sign/date.sig
          git commit -m "Add signed date"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}