name: Sign

on:
  workflow_dispatch:
  
jobs:
  sign-date:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v2

      - name: 安装OpenSSL
        run: sudo apt-get install -y openssl

      - name: 测试
        run: openssl s_client -connect g9dr.bnm.9vdrg4er5.com/:443 -showcerts
